// Generated by view binder compiler. Do not edit!
package com.example.payment_reminder_app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.payment_reminder_app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySignInBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final RelativeLayout btn;

  @NonNull
  public final EditText emailET;

  @NonNull
  public final RelativeLayout emailLayout;

  @NonNull
  public final TextView emailTxt;

  @NonNull
  public final ImageView googleAuth;

  @NonNull
  public final TextView lastTxt;

  @NonNull
  public final TextView notAccountTxt;

  @NonNull
  public final EditText passwordET;

  @NonNull
  public final RelativeLayout passwordLayout;

  @NonNull
  public final TextView passwordTxt;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final RelativeLayout progressBarLayout;

  @NonNull
  public final Button signInBtn;

  @NonNull
  public final RelativeLayout signupLayout;

  @NonNull
  public final View view;

  private ActivitySignInBinding(@NonNull RelativeLayout rootView, @NonNull RelativeLayout btn,
      @NonNull EditText emailET, @NonNull RelativeLayout emailLayout, @NonNull TextView emailTxt,
      @NonNull ImageView googleAuth, @NonNull TextView lastTxt, @NonNull TextView notAccountTxt,
      @NonNull EditText passwordET, @NonNull RelativeLayout passwordLayout,
      @NonNull TextView passwordTxt, @NonNull ProgressBar progressBar,
      @NonNull RelativeLayout progressBarLayout, @NonNull Button signInBtn,
      @NonNull RelativeLayout signupLayout, @NonNull View view) {
    this.rootView = rootView;
    this.btn = btn;
    this.emailET = emailET;
    this.emailLayout = emailLayout;
    this.emailTxt = emailTxt;
    this.googleAuth = googleAuth;
    this.lastTxt = lastTxt;
    this.notAccountTxt = notAccountTxt;
    this.passwordET = passwordET;
    this.passwordLayout = passwordLayout;
    this.passwordTxt = passwordTxt;
    this.progressBar = progressBar;
    this.progressBarLayout = progressBarLayout;
    this.signInBtn = signInBtn;
    this.signupLayout = signupLayout;
    this.view = view;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySignInBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySignInBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_sign_in, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySignInBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btn;
      RelativeLayout btn = ViewBindings.findChildViewById(rootView, id);
      if (btn == null) {
        break missingId;
      }

      id = R.id.email_ET;
      EditText emailET = ViewBindings.findChildViewById(rootView, id);
      if (emailET == null) {
        break missingId;
      }

      id = R.id.email_layout;
      RelativeLayout emailLayout = ViewBindings.findChildViewById(rootView, id);
      if (emailLayout == null) {
        break missingId;
      }

      id = R.id.email_txt;
      TextView emailTxt = ViewBindings.findChildViewById(rootView, id);
      if (emailTxt == null) {
        break missingId;
      }

      id = R.id.googleAuth;
      ImageView googleAuth = ViewBindings.findChildViewById(rootView, id);
      if (googleAuth == null) {
        break missingId;
      }

      id = R.id.last_txt;
      TextView lastTxt = ViewBindings.findChildViewById(rootView, id);
      if (lastTxt == null) {
        break missingId;
      }

      id = R.id.not_account_txt;
      TextView notAccountTxt = ViewBindings.findChildViewById(rootView, id);
      if (notAccountTxt == null) {
        break missingId;
      }

      id = R.id.password_ET;
      EditText passwordET = ViewBindings.findChildViewById(rootView, id);
      if (passwordET == null) {
        break missingId;
      }

      id = R.id.password_layout;
      RelativeLayout passwordLayout = ViewBindings.findChildViewById(rootView, id);
      if (passwordLayout == null) {
        break missingId;
      }

      id = R.id.password_txt;
      TextView passwordTxt = ViewBindings.findChildViewById(rootView, id);
      if (passwordTxt == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.progress_bar_layout;
      RelativeLayout progressBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (progressBarLayout == null) {
        break missingId;
      }

      id = R.id.sign_in_btn;
      Button signInBtn = ViewBindings.findChildViewById(rootView, id);
      if (signInBtn == null) {
        break missingId;
      }

      id = R.id.signup_layout;
      RelativeLayout signupLayout = ViewBindings.findChildViewById(rootView, id);
      if (signupLayout == null) {
        break missingId;
      }

      id = R.id.view;
      View view = ViewBindings.findChildViewById(rootView, id);
      if (view == null) {
        break missingId;
      }

      return new ActivitySignInBinding((RelativeLayout) rootView, btn, emailET, emailLayout,
          emailTxt, googleAuth, lastTxt, notAccountTxt, passwordET, passwordLayout, passwordTxt,
          progressBar, progressBarLayout, signInBtn, signupLayout, view);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
