// Generated by view binder compiler. Do not edit!
package com.example.payment_reminder_app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.payment_reminder_app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySignUpBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final RelativeLayout btn;

  @NonNull
  public final EditText cmPasswordET;

  @NonNull
  public final RelativeLayout confirmPassLayout;

  @NonNull
  public final TextView confirmPassTxt;

  @NonNull
  public final Button continueBtn;

  @NonNull
  public final EditText emailET;

  @NonNull
  public final RelativeLayout emailLayout;

  @NonNull
  public final TextView emailTxt;

  @NonNull
  public final TextView lastTxt;

  @NonNull
  public final EditText passwordET;

  @NonNull
  public final RelativeLayout passwordLayout;

  @NonNull
  public final TextView passwordTxt;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final RelativeLayout progressBarLayout;

  @NonNull
  public final TextView signInTxt;

  @NonNull
  public final RelativeLayout signupLayout;

  private ActivitySignUpBinding(@NonNull RelativeLayout rootView, @NonNull RelativeLayout btn,
      @NonNull EditText cmPasswordET, @NonNull RelativeLayout confirmPassLayout,
      @NonNull TextView confirmPassTxt, @NonNull Button continueBtn, @NonNull EditText emailET,
      @NonNull RelativeLayout emailLayout, @NonNull TextView emailTxt, @NonNull TextView lastTxt,
      @NonNull EditText passwordET, @NonNull RelativeLayout passwordLayout,
      @NonNull TextView passwordTxt, @NonNull ProgressBar progressBar,
      @NonNull RelativeLayout progressBarLayout, @NonNull TextView signInTxt,
      @NonNull RelativeLayout signupLayout) {
    this.rootView = rootView;
    this.btn = btn;
    this.cmPasswordET = cmPasswordET;
    this.confirmPassLayout = confirmPassLayout;
    this.confirmPassTxt = confirmPassTxt;
    this.continueBtn = continueBtn;
    this.emailET = emailET;
    this.emailLayout = emailLayout;
    this.emailTxt = emailTxt;
    this.lastTxt = lastTxt;
    this.passwordET = passwordET;
    this.passwordLayout = passwordLayout;
    this.passwordTxt = passwordTxt;
    this.progressBar = progressBar;
    this.progressBarLayout = progressBarLayout;
    this.signInTxt = signInTxt;
    this.signupLayout = signupLayout;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySignUpBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySignUpBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_sign_up, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySignUpBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btn;
      RelativeLayout btn = ViewBindings.findChildViewById(rootView, id);
      if (btn == null) {
        break missingId;
      }

      id = R.id.cm_password_ET;
      EditText cmPasswordET = ViewBindings.findChildViewById(rootView, id);
      if (cmPasswordET == null) {
        break missingId;
      }

      id = R.id.confirm_pass_layout;
      RelativeLayout confirmPassLayout = ViewBindings.findChildViewById(rootView, id);
      if (confirmPassLayout == null) {
        break missingId;
      }

      id = R.id.confirm_pass_txt;
      TextView confirmPassTxt = ViewBindings.findChildViewById(rootView, id);
      if (confirmPassTxt == null) {
        break missingId;
      }

      id = R.id.continue_btn;
      Button continueBtn = ViewBindings.findChildViewById(rootView, id);
      if (continueBtn == null) {
        break missingId;
      }

      id = R.id.email_ET;
      EditText emailET = ViewBindings.findChildViewById(rootView, id);
      if (emailET == null) {
        break missingId;
      }

      id = R.id.email_layout;
      RelativeLayout emailLayout = ViewBindings.findChildViewById(rootView, id);
      if (emailLayout == null) {
        break missingId;
      }

      id = R.id.email_txt;
      TextView emailTxt = ViewBindings.findChildViewById(rootView, id);
      if (emailTxt == null) {
        break missingId;
      }

      id = R.id.last_txt;
      TextView lastTxt = ViewBindings.findChildViewById(rootView, id);
      if (lastTxt == null) {
        break missingId;
      }

      id = R.id.password_ET;
      EditText passwordET = ViewBindings.findChildViewById(rootView, id);
      if (passwordET == null) {
        break missingId;
      }

      id = R.id.password_layout;
      RelativeLayout passwordLayout = ViewBindings.findChildViewById(rootView, id);
      if (passwordLayout == null) {
        break missingId;
      }

      id = R.id.password_txt;
      TextView passwordTxt = ViewBindings.findChildViewById(rootView, id);
      if (passwordTxt == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.progress_bar_layout;
      RelativeLayout progressBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (progressBarLayout == null) {
        break missingId;
      }

      id = R.id.sign_in_txt;
      TextView signInTxt = ViewBindings.findChildViewById(rootView, id);
      if (signInTxt == null) {
        break missingId;
      }

      id = R.id.signup_layout;
      RelativeLayout signupLayout = ViewBindings.findChildViewById(rootView, id);
      if (signupLayout == null) {
        break missingId;
      }

      return new ActivitySignUpBinding((RelativeLayout) rootView, btn, cmPasswordET,
          confirmPassLayout, confirmPassTxt, continueBtn, emailET, emailLayout, emailTxt, lastTxt,
          passwordET, passwordLayout, passwordTxt, progressBar, progressBarLayout, signInTxt,
          signupLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
