// Generated by view binder compiler. Do not edit!
package com.example.payment_reminder_app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.payment_reminder_app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAddBillBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final Button cancelBtn;

  @NonNull
  public final Button datePickerButton;

  @NonNull
  public final Button datePickerButton2;

  @NonNull
  public final TextView description;

  @NonNull
  public final EditText descriptionET;

  @NonNull
  public final RelativeLayout descriptionLayout;

  @NonNull
  public final TextView dueDate;

  @NonNull
  public final RelativeLayout dueDateLayout;

  @NonNull
  public final TextView issueDate;

  @NonNull
  public final RelativeLayout issueDateLayout;

  @NonNull
  public final Button submitBtn;

  @NonNull
  public final TextView title;

  @NonNull
  public final EditText titleET;

  @NonNull
  public final RelativeLayout titleLayout;

  @NonNull
  public final TextView upperTxt;

  private ActivityAddBillBinding(@NonNull RelativeLayout rootView, @NonNull Button cancelBtn,
      @NonNull Button datePickerButton, @NonNull Button datePickerButton2,
      @NonNull TextView description, @NonNull EditText descriptionET,
      @NonNull RelativeLayout descriptionLayout, @NonNull TextView dueDate,
      @NonNull RelativeLayout dueDateLayout, @NonNull TextView issueDate,
      @NonNull RelativeLayout issueDateLayout, @NonNull Button submitBtn, @NonNull TextView title,
      @NonNull EditText titleET, @NonNull RelativeLayout titleLayout, @NonNull TextView upperTxt) {
    this.rootView = rootView;
    this.cancelBtn = cancelBtn;
    this.datePickerButton = datePickerButton;
    this.datePickerButton2 = datePickerButton2;
    this.description = description;
    this.descriptionET = descriptionET;
    this.descriptionLayout = descriptionLayout;
    this.dueDate = dueDate;
    this.dueDateLayout = dueDateLayout;
    this.issueDate = issueDate;
    this.issueDateLayout = issueDateLayout;
    this.submitBtn = submitBtn;
    this.title = title;
    this.titleET = titleET;
    this.titleLayout = titleLayout;
    this.upperTxt = upperTxt;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAddBillBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAddBillBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_add_bill, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAddBillBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cancel_btn;
      Button cancelBtn = ViewBindings.findChildViewById(rootView, id);
      if (cancelBtn == null) {
        break missingId;
      }

      id = R.id.datePickerButton;
      Button datePickerButton = ViewBindings.findChildViewById(rootView, id);
      if (datePickerButton == null) {
        break missingId;
      }

      id = R.id.datePickerButton2;
      Button datePickerButton2 = ViewBindings.findChildViewById(rootView, id);
      if (datePickerButton2 == null) {
        break missingId;
      }

      id = R.id.description;
      TextView description = ViewBindings.findChildViewById(rootView, id);
      if (description == null) {
        break missingId;
      }

      id = R.id.description_ET;
      EditText descriptionET = ViewBindings.findChildViewById(rootView, id);
      if (descriptionET == null) {
        break missingId;
      }

      id = R.id.description_layout;
      RelativeLayout descriptionLayout = ViewBindings.findChildViewById(rootView, id);
      if (descriptionLayout == null) {
        break missingId;
      }

      id = R.id.due_date;
      TextView dueDate = ViewBindings.findChildViewById(rootView, id);
      if (dueDate == null) {
        break missingId;
      }

      id = R.id.due_date_layout;
      RelativeLayout dueDateLayout = ViewBindings.findChildViewById(rootView, id);
      if (dueDateLayout == null) {
        break missingId;
      }

      id = R.id.issue_date;
      TextView issueDate = ViewBindings.findChildViewById(rootView, id);
      if (issueDate == null) {
        break missingId;
      }

      id = R.id.issue_date_layout;
      RelativeLayout issueDateLayout = ViewBindings.findChildViewById(rootView, id);
      if (issueDateLayout == null) {
        break missingId;
      }

      id = R.id.submit_btn;
      Button submitBtn = ViewBindings.findChildViewById(rootView, id);
      if (submitBtn == null) {
        break missingId;
      }

      id = R.id.title;
      TextView title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      id = R.id.title_ET;
      EditText titleET = ViewBindings.findChildViewById(rootView, id);
      if (titleET == null) {
        break missingId;
      }

      id = R.id.title_layout;
      RelativeLayout titleLayout = ViewBindings.findChildViewById(rootView, id);
      if (titleLayout == null) {
        break missingId;
      }

      id = R.id.upper_txt;
      TextView upperTxt = ViewBindings.findChildViewById(rootView, id);
      if (upperTxt == null) {
        break missingId;
      }

      return new ActivityAddBillBinding((RelativeLayout) rootView, cancelBtn, datePickerButton,
          datePickerButton2, description, descriptionET, descriptionLayout, dueDate, dueDateLayout,
          issueDate, issueDateLayout, submitBtn, title, titleET, titleLayout, upperTxt);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
