// Generated by view binder compiler. Do not edit!
package com.example.payment_reminder_app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.payment_reminder_app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityForgetPasswordBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final ImageView backBtn;

  @NonNull
  public final EditText emailET;

  @NonNull
  public final TextView emailTxt;

  @NonNull
  public final TextView forgetDec;

  @NonNull
  public final ImageView img;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final Button resetPass;

  @NonNull
  public final TextView text;

  private ActivityForgetPasswordBinding(@NonNull RelativeLayout rootView,
      @NonNull ImageView backBtn, @NonNull EditText emailET, @NonNull TextView emailTxt,
      @NonNull TextView forgetDec, @NonNull ImageView img, @NonNull ProgressBar progressBar,
      @NonNull Button resetPass, @NonNull TextView text) {
    this.rootView = rootView;
    this.backBtn = backBtn;
    this.emailET = emailET;
    this.emailTxt = emailTxt;
    this.forgetDec = forgetDec;
    this.img = img;
    this.progressBar = progressBar;
    this.resetPass = resetPass;
    this.text = text;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityForgetPasswordBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityForgetPasswordBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_forget_password, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityForgetPasswordBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.back_btn;
      ImageView backBtn = ViewBindings.findChildViewById(rootView, id);
      if (backBtn == null) {
        break missingId;
      }

      id = R.id.email_ET;
      EditText emailET = ViewBindings.findChildViewById(rootView, id);
      if (emailET == null) {
        break missingId;
      }

      id = R.id.email_txt;
      TextView emailTxt = ViewBindings.findChildViewById(rootView, id);
      if (emailTxt == null) {
        break missingId;
      }

      id = R.id.forget_dec;
      TextView forgetDec = ViewBindings.findChildViewById(rootView, id);
      if (forgetDec == null) {
        break missingId;
      }

      id = R.id.img;
      ImageView img = ViewBindings.findChildViewById(rootView, id);
      if (img == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.reset_pass;
      Button resetPass = ViewBindings.findChildViewById(rootView, id);
      if (resetPass == null) {
        break missingId;
      }

      id = R.id.text;
      TextView text = ViewBindings.findChildViewById(rootView, id);
      if (text == null) {
        break missingId;
      }

      return new ActivityForgetPasswordBinding((RelativeLayout) rootView, backBtn, emailET,
          emailTxt, forgetDec, img, progressBar, resetPass, text);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
