// Generated by view binder compiler. Do not edit!
package com.example.payment_reminder_app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.SearchView;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.payment_reminder_app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBillBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final TextView addBillTxt;

  @NonNull
  public final Button addCircle;

  @NonNull
  public final Button backBtn;

  @NonNull
  public final RelativeLayout mainLayout;

  @NonNull
  public final RecyclerView recyclerView;

  @NonNull
  public final SearchView searchView;

  @NonNull
  public final RelativeLayout searchViewLayout;

  @NonNull
  public final RelativeLayout upperLayout;

  private ActivityBillBinding(@NonNull RelativeLayout rootView, @NonNull TextView addBillTxt,
      @NonNull Button addCircle, @NonNull Button backBtn, @NonNull RelativeLayout mainLayout,
      @NonNull RecyclerView recyclerView, @NonNull SearchView searchView,
      @NonNull RelativeLayout searchViewLayout, @NonNull RelativeLayout upperLayout) {
    this.rootView = rootView;
    this.addBillTxt = addBillTxt;
    this.addCircle = addCircle;
    this.backBtn = backBtn;
    this.mainLayout = mainLayout;
    this.recyclerView = recyclerView;
    this.searchView = searchView;
    this.searchViewLayout = searchViewLayout;
    this.upperLayout = upperLayout;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBillBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBillBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_bill, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBillBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.add_bill_txt;
      TextView addBillTxt = ViewBindings.findChildViewById(rootView, id);
      if (addBillTxt == null) {
        break missingId;
      }

      id = R.id.add_circle;
      Button addCircle = ViewBindings.findChildViewById(rootView, id);
      if (addCircle == null) {
        break missingId;
      }

      id = R.id.back_btn;
      Button backBtn = ViewBindings.findChildViewById(rootView, id);
      if (backBtn == null) {
        break missingId;
      }

      id = R.id.main_layout;
      RelativeLayout mainLayout = ViewBindings.findChildViewById(rootView, id);
      if (mainLayout == null) {
        break missingId;
      }

      id = R.id.recycler_view;
      RecyclerView recyclerView = ViewBindings.findChildViewById(rootView, id);
      if (recyclerView == null) {
        break missingId;
      }

      id = R.id.searchView;
      SearchView searchView = ViewBindings.findChildViewById(rootView, id);
      if (searchView == null) {
        break missingId;
      }

      id = R.id.search_view_layout;
      RelativeLayout searchViewLayout = ViewBindings.findChildViewById(rootView, id);
      if (searchViewLayout == null) {
        break missingId;
      }

      id = R.id.upper_layout;
      RelativeLayout upperLayout = ViewBindings.findChildViewById(rootView, id);
      if (upperLayout == null) {
        break missingId;
      }

      return new ActivityBillBinding((RelativeLayout) rootView, addBillTxt, addCircle, backBtn,
          mainLayout, recyclerView, searchView, searchViewLayout, upperLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
