// Generated by view binder compiler. Do not edit!
package com.example.payment_reminder_app.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.payment_reminder_app.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ShowDialogBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final AppCompatButton cancelBtn;

  @NonNull
  public final Button paid;

  @NonNull
  public final TextView points;

  @NonNull
  public final ImageView pointsImage;

  @NonNull
  public final TextView titleTextPoints;

  @NonNull
  public final Button wait;

  private ShowDialogBinding(@NonNull RelativeLayout rootView, @NonNull AppCompatButton cancelBtn,
      @NonNull Button paid, @NonNull TextView points, @NonNull ImageView pointsImage,
      @NonNull TextView titleTextPoints, @NonNull Button wait) {
    this.rootView = rootView;
    this.cancelBtn = cancelBtn;
    this.paid = paid;
    this.points = points;
    this.pointsImage = pointsImage;
    this.titleTextPoints = titleTextPoints;
    this.wait = wait;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ShowDialogBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ShowDialogBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.show_dialog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ShowDialogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cancel_btn;
      AppCompatButton cancelBtn = ViewBindings.findChildViewById(rootView, id);
      if (cancelBtn == null) {
        break missingId;
      }

      id = R.id.paid;
      Button paid = ViewBindings.findChildViewById(rootView, id);
      if (paid == null) {
        break missingId;
      }

      id = R.id.points;
      TextView points = ViewBindings.findChildViewById(rootView, id);
      if (points == null) {
        break missingId;
      }

      id = R.id.points_image;
      ImageView pointsImage = ViewBindings.findChildViewById(rootView, id);
      if (pointsImage == null) {
        break missingId;
      }

      id = R.id.title_text_points;
      TextView titleTextPoints = ViewBindings.findChildViewById(rootView, id);
      if (titleTextPoints == null) {
        break missingId;
      }

      id = R.id.wait;
      Button wait = ViewBindings.findChildViewById(rootView, id);
      if (wait == null) {
        break missingId;
      }

      return new ShowDialogBinding((RelativeLayout) rootView, cancelBtn, paid, points, pointsImage,
          titleTextPoints, wait);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
